### ISSUE TITLE
macOS Ventura

### ISSUE THREAD

**Issue by cvega48** [msbence/hackintosh-DellLatitude5400#17]
@msbence Any chance you might try installing Ventura on your Latitude 5400 this time? :)

**Comment by msbence** [comment]
hi @cvega48 !
Yes... so the thing is, shortly after I got my company Mac, I changed it to a Latitude 5420 because my 5400 Hackintosh was more stable than that shitty Apple hardware :DDD
Of course I won't experiment with the company laptop, but in the meantime I got my Latitude 7430 and I will retire my 5400. But before I do so (and abandon this repo completly), I want to update it one last time. So yeah, expect a Ventura release in the following 1-2 week. :)

**Comment by cvega48** [comment]
I tried this EFI for Ventura and one thing I noticed that works very well is the SD Card Reader. Maybe you can use this EFI to see if you can make SD Card work on your setup as well. Thanks for your help on the 5400. I have a work laptop as well, but use a different NVMe to use my Hackintosh build on it that way I dont tinker with corporate Windows Settings. :)

https://github.com/Dugganclock/Dell-Latitude-5400-Hackintosh-OpenCore

**Comment by msbence** [comment]
I have a strange feeling, that repo heavily uses mine as a base... :D
So I started working on this, and to be honest a lot of things changed since I last touched a hackintosh... The latest macOS what I was able to install is Catalina... I tried the EFI what you sent, and the installer booted (which with mine could not).
Either I redo my EFI from scratch, or just let it go, archive it, and done. Because if an other repo exists which works, I do not see the point of keeping it... Back in the time when I created this, no other repo existed. Now I just cannot simply see the point. But maybe I'll waste some time, just as a challenge...

**Comment by msbence** [comment]
I did several noob mistakes...  _facepalm_
So I produly present this - probably the last - release, with Ventura support, and I also managed to fix almost everything :)
If you could test it @cvega48 that would be awesome! <3

**Comment by cvega48** [comment]
I booted with your EFI on my same hackintosh. Everything works as it should and as you mentioned on your post. But the Trackpad is still not working. When I move my finger on the trackpad, the keyboard lights up recognizing movement but the cursor and the buttons are not working. Not sure if maybe there is a BIOS setting I might need to tweak.

I have another SSD where I have Windows, when I boot there, trackpad works great.

**Comment by cvega48** [comment]
Another thing I have seen happening on Ventura is this message every now and then.
![image](https://user-images.githubusercontent.com/55467816/202695432-bb5a2297-ff67-4254-bb4b-3c31cd85519e.png)
Bluetooth devices stop working when this happens. Sometimes it autocorrects it self after a while.
If I restart everything back to normal.

**Comment by alarifgit** [comment]
@msbence Your Ventura files are working perfectly for me, but I am however going to build my own from scratch with some borrowing of your work, as to me the brightness keys shouldn't be too hard to get working at all 

EDIT: After staying up to 4am I have managed to get my own Ventura build working, with brightness controls working from the dell brightness keys, and essentially anything you had working from your build.
