### ISSUE TITLE
Bt and WiFi 

### ISSUE THREAD

**Issue by jaywhojaycee** [msbence/hackintosh-DellLatitude5400#6]
How do I get the bt and WiFi to work it tells me Bluetooth is not available at this time

**Comment by msbence** [comment]
Hi @jaywhojaycee ! What kind of wifi/bt adapter do you have?

**Comment by jaywhojaycee** [comment]
@msbence i have the stock that came with the laptop I thought everything was working out the box

**Comment by msbence** [comment]
@jaywhojaycee no. this way I don't even know how your wifi works :D
So the thing is that the stock is an intel one. Back when I started this project Intel cards wasn't supported at all.
Now, I assume you could take a look at https://github.com/OpenIntelWireless as they had success with Intel cards.
I bought an BCM94360NG which is supported out of the box. That's why it's working for me :)

**Comment by jaywhojaycee** [comment]
@msbence so with the BCM94360NG the Bluetooth will work ?

**Comment by msbence** [comment]
@jaywhojaycee definitely. I use it, (BT headphones and BT Magic Mouse 2) works fine. No additional kexts needed.

**Comment by jaywhojaycee** [comment]
@msbence thanks nice work by the way you think you will ever get the finger print scanner to work ?

**Comment by msbence** [comment]
@jaywhojaycee that's another issue. I don't think 3rd party readers will work with macos in the near future.
And my notebook isn't equipped with an FP reader, so I can't even experiment :(

**Comment by jaywhojaycee** [comment]
@msbence do you kno if face time and I message work for some reason my 5400 didn’t come wit a web cam hopefully I can install one

**Comment by msbence** [comment]
I think it should work, but it's not working for me because my AppleID is blacklisted. This is because of my early hackintosh experiments (os x lion, with clover... a long time ago). The apps itself are working, just try login with your apple id. If something is wrong, I can't really help but consult the guide here: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

**Comment by msbence** [comment]
This is going offtopic, so I close it. If you have problems with iServices please open a separate issue.
