### ISSUE TITLE
Apple DRM not working 

### ISSUE THREAD

**Issue by jaywhojaycee** [msbence/hackintosh-DellLatitude5400#8]
Applet DRM not working so can’t play Netflix, Apple TV etc. using the Safari browser

**Comment by msbence** [comment]
It won't work. See https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding for more info.
If you have a dGPU you can try some other methods, but Whatevergreen's patch is not working under Big Sur.

I'll mention this in the not working section. I didn't notice it because I only use Safari to download some usable browser. :)

**Comment by jaywhojaycee** [comment]
@msbence so it’s impossible to get it working in the dell latitude 5400

**Comment by msbence** [comment]
As long as the whatevergreen patch is not working, yes, it's impossible.
